# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9f70f67bfa4701c87496fcc2967b477f8584ffa8d6b64b7fb736b64d150a4c8726da4faa17fd6a069b9b7b241cc08c4e4e23f54c7dcc5c481c84aa6a299719ff

test:
  secret_key_base: d9547adbfa44e21e3e0684aac53f4b5047cbb7ef7c6e9f245db55d96c8be14487c0d4c3b527cf2e5b20804afacd94dc0f0191174bdeca7e8af6c7c6d7fe18140

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
